config/routes.rb
Rails.application.routes.draw do
  devise_for :users

     resources :categories
     resources :products

     resources :coupons
     resources :promos do
       collection do
         get :get_promo_target
       end
     end

     resources :transactions
     resources :vendors
     resources :carts

  root to: "homes#index"
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
	accepts_nested_attributes_for :products

	belongs_to :created_by_user, :class_name => "User", :foreign_key => :created_by
	#belongs_to :updated_by_user, :class_name => "User", :foreign_key => :updated_by

	validates :category_name, :presence => {:message => "Tidak boleh kosong"}

	def set_created_by(user)
		self.created_by_user = user
		return self
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
		@categories = Category.order("created_at DESC")
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(params_category).set_created_by(current_user)
		if @category.valid?
			@category.save
			redirect_to categories_path, :flash => {:notice => "Data berhasil disimpan."}
		else
			flash[:error] = @category.errors.full_messages.to_sentence
			render 'new'
		end
	end

	def show
		@category = Category.find(params[:id])
		@products = @category.products
	end

	private

	def params_category
		params.require(:category).permit(:category_name)
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/shared/_form.html.erb
<%= f.label :category_name %>
<%= f.text_field :category_name %>
<br/>
<%= f.submit %>

app/views/categories/shared/_result_products.html.erb
<table border="1">
	<tr>
		<td>Vendor</td>
		<td>Kode Produk</td>
		<td>Nama Produk</td>
		<td>Qty</td>
		<td>Harga Satuan</td>
	</tr>
	<% if products.blank? %>
		<tr>
			<td colspan="3">Data tidak ditemukan</td>
		</tr>
	<% else %>
		<% products.each do |product| %>
			<tr>
				<td><%= product.vendor.vendor_name %></td>
				<td><%= product.item_code %></td>
				<td><%= product.item_description %></td>
				<td><%= product.item_quantity %></td>
				<td><%= product.item_price %></td>
			</tr>
		<% end %>
	<% end %>
</table>

<%= link_to "Tambah Product", new_product_path(:category => category) %>

app/views/categories/shared/_results.html.erb
<p id="notice"><%= flash[:notice] %></p>
<table border="1">
	<tr>
		<td>Nama Kategori</td>
		<td>Created By</td>
	</tr>
	<% if categories.blank? %>
		<tr>
			<td colspan="2">Data tidak ditemukan</td>
		</tr>
	<% else %>
		<% categories.each do |cat| %>
			<tr>
				<td><%= link_to "#{cat.category_name}", category_path(cat) %></td>
				<td><%= cat.created_by_user.email %></td>
			</tr>
		<% end %>
	<% end %>
</table>

<%= link_to "Tambah Kategory", new_category_path %>