config/routes.rb
Rails.application.routes.draw do
  devise_for :users

     resources :categories
     resources :products

     resources :coupons
     resources :promos do
       collection do
         get :get_promo_target
       end
     end

     resources :transactions
     resources :vendors
     resources :carts

  root to: "homes#index"
end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
	belongs_to :coupon_customer, :class_name => "User", :foreign_key => :coupon_customer_id
	belongs_to :created_by_user, :class_name => "User", :foreign_key => :created_by

	validates :code_coupon,
						:presence => {:message => "Tidak boleh kosong"},
						:uniqueness => {:case_sensitif => false, :message => "sudah tersedia"}
	validates :description, :presence => {:message => "Tidak boleh kosong"}
	validates :value_coupon, :presence => {:message => "Tidak boleh kosong"}
	validates :start_date_active_coupon, :presence => {:message => "Tidak boleh kosong"}
	validates :end_date_active_coupon, :presence => {:message => "Tidak boleh kosong"}
	validates :user_coupon, :presence => {:message => "Tidak boleh kosong"}
	validate :format_date_is_valid_datetime

  def format_date_is_valid_datetime
    errors.add(:start_date_active_coupon, 'Format tanggal tidak valid') if self.start_date_active_coupon.present? && !self.start_date_active_coupon.to_date.is_a?(Date)
    errors.add(:end_date_active_coupon, 'Format tanggal tidak valid') if self.end_date_active_coupon.present? && !self.end_date_active_coupon.to_date.is_a?(Date)
  end

  def get_validate_coupon
    (self.start_date_active_coupon.to_datetime.strftime("%d-%m-%Y").to_date..self.end_date_active_coupon.to_datetime.strftime("%d-%m-%Y").to_date).cover?(Time.now.strftime("%d-%m-%Y").to_date)
  end
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
	def index
		@coupons = Coupon.order("created_at DESC")
	end

	def new
		@coupon = Coupon.new
	end

	def create
		@coupon = Coupon.new(params_coupon)
		if @coupon.valid?
			@coupon.save
			redirect_to coupons_path, :flash => {:notice => "Data berhasil disimpan"}
		else
			flash[:error] = @coupon.errors.full_messages.to_sentence
			render "new"
		end
	end

	private

	def params_coupon
		params.require(:coupon).permit(:code_coupon, :description, :value_coupon, :start_date_active_coupon, :end_date_active_coupon, :user_coupon)
	end
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/views/coupons/shared/_form.html.erb
<%= f.label :code_coupon %>
<%= f.text_field :code_coupon %><br/>
<%= f.label :description %>
<%= f.text_field :description %><br/>
<%= f.label :value_coupon %>
<%= f.text_field :value_coupon %><br/>
<%= f.label :start_date_active_coupon %>
<%= f.text_field :start_date_active_coupon %><br/>
<%= f.label :end_date_active_coupon %>
<%= f.text_field :end_date_active_coupon %><br/>
<%= f.label :user_coupon %>
<%= f.text_field :user_coupon %><br/>

<br/>
<%= f.submit %>

app/views/coupons/shared/_results.html.erb
<p id="notice"><%= flash[:notice] %></p>
<table border="1">
	<tr>
		<td>Kode Kupon</td>
		<td>Description</td>
		<td>Value Kupon</td>
		<td>Active Start Kupon</td>
		<td>Active End Kupon</td>
		<td>User</td>
	</tr>
	<% if coupons.blank? %>
		<tr>
			<td colspan="6">Data tidak ditemukan</td>
		</tr>
	<% else %>
		<% coupons.each do |coupon| %>
			<tr>
				<td><%= coupon.code_coupon %></td>
				<td><%= coupon.description %></td>
				<td><%= coupon.value_coupon %></td>
				<td><%= coupon.start_date_active_coupon.localtime.strftime("%d %B %Y") %></td>
				<td><%= coupon.end_date_active_coupon.localtime.strftime("%d %B %Y") %></td>
				<td><%= coupon.user_coupon_value.email %></td>
			</tr>
		<% end %>
	<% end %>
</table>

<%= link_to "Tambah Coupon", new_coupon_path %>