config/routes.rb
Rails.application.routes.draw do
  devise_for :users

     resources :categories
     resources :products

     resources :coupons
     resources :promos do
       collection do
         get :get_promo_target
       end
     end

     resources :transactions
     resources :vendors
     resources :carts

  root to: "homes#index"
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
	has_many :products
	belongs_to :created_by_user, :class_name => "User", :foreign_key => :created_by

	def set_created_by(user)
		self.created_by_user = user
		return self
	end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
	def index
		@vendors = Vendor.order("created_at DESC")
	end

	def new
		@vendor = Vendor.new
	end

	def create
		@vendor = Vendor.new(params_vendor).set_created_by(current_user)
		if @vendor.valid?
			@vendor.save
			redirect_to vendors_path, :flash => {:notice => "Data berhasil disimpan."}
		else
			flash[:error] = @vendor.errors.full_messages.to_sentence
			render 'new'
		end
	end

	private

	def params_vendor
		params.require(:vendor).permit(:vendor_name)
	end
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/shared/_form.html.erb
<%= f.label :vendor_name %>
<%= f.text_field :vendor_name %><br/>
<br/>
<%= f.submit %>

app/views/vendors/shared/_results.html.erb
<p id="notice"><%= flash[:notice] %></p>
<table border="1">
	<tr>
		<td>Vendor Name</td>
	</tr>
	<% if vendors.blank? %>
		<tr>
			<td colspan="6">Data tidak ditemukan</td>
		</tr>
	<% else %>
		<% vendors.each do |vendor| %>
			<tr>
				<td><%= vendor.vendor_name %></td>
			</tr>
		<% end %>
	<% end %>
</table>

<%= link_to "Tambah vendor", new_vendor_path %>