config/routes.rb
Rails.application.routes.draw do
  devise_for :users

     resources :categories
     resources :products

     resources :coupons
     resources :promos do
       collection do
         get :get_promo_target
       end
     end

     resources :transactions
     resources :vendors
     resources :carts

  root to: "homes#index"
end

app/models/promo.rb
class Promo < ActiveRecord::Base
	belongs_to :created_by_user, :class_name => "User", :foreign_key => :created_by
	has_many :promo_details
  accepts_nested_attributes_for :promo_details

	validates :promo_description, :presence => {:message => "Tidak boleh kosong"}
	validates :start_date_promo, :presence => {:message => "Tidak boleh kosong"}
	validates :end_date_promo, :presence => {:message => "Tidak boleh kosong"}
	validate :format_date_is_valid_datetime

  def format_date_is_valid_datetime
    errors.add(:start_date_promo, 'Format tanggal tidak valid') if self.start_date_promo.present? && !self.start_date_promo.to_date.is_a?(Date)
    errors.add(:end_date_promo, 'Format tanggal tidak valid') if self.end_date_promo.present? && !self.end_date_promo.to_date.is_a?(Date)
  end

  def check_expired_promo
  	Time.now.to_date >= self.start_date_promo.to_date && Time.now.to_date <= self.end_date_promo
  end
end

app/controllers/promos_controller.rb
class PromosController < ApplicationController
	def index
		@promos = Promo.order("created_at DESC")
	end

	def new
		@promo = Promo.new
		@promo_detail = PromoDetail.new
		@promo.promo_details.build
		@products = Product.where("products.id NOT IN (SELECT value_promo FROM promo_details WHERE is_active = true)")
	end

	def create
		@promo = Promo.new(params_promo)
		if @promo.valid?
			@promo.save
			redirect_to promos_path, :flash => {:notice => "Data berhasil disimpan"}
		else
			flash[:error] = @promo.errors.full_messages.to_sentence
			render "new"
		end
	end

	def show
		@promo = Promo.find(params[:id])
	end

	def get_promo_target
		@products = Product.where("products.id NOT IN (SELECT value_promo FROM promo_details WHERE is_active = true)")
		render :layout => false
	end

	private
	def params_promo
		params.require(:promo).permit(:code_promo, :promo_description, :start_date_promo, :end_date_promo, :promo_details_attributes => [:type_promo, :value_promo, :quantity_promo, :type_target, :value_target, :quantity_target])
	end
end

app/helpers/promos_helper.rb
module PromosHelper
end

app/views/promos/shared/_form.html.erb
<%= f.label :code_promo %>
<%= f.text_field :code_promo %>
<%= f.label :promo_description %>
<%= f.text_field :promo_description %>
<%= f.label :start_date_promo %>
<%= f.date_field :start_date_promo %>
<%= f.label :end_date_promo %>
<%= f.date_field :end_date_promo %>
<br/><br/>
<table border="1">
	<tr>
		<td>Select</td>
		<td>Product Promo</td>
		<td>Type Promo</td>
		<td>Qty Promo</td>
		<td>Type Target</td>
		<td>Value Target</td>
		<td>Qty Target</td>
	</tr>
	<% @products.each_with_index do |product, i| %>
		<%= f.fields_for :promo_details, @promo_detail do |f_det| %>
			<tr>
				<td><%= check_box_tag "select_promo_product[#{i}]", i, false, :onclick => "get_enable_disable_promo_product(this)"  %></td>
				<td><%= f_det.select :value_promo, @products.collect{|prod| ["(#{prod.vendor.vendor_name}) #{prod.item_code} - #{prod.item_description}", prod.id] }, {}, :disabled => true %></td>
				<td><%= f_det.select :type_promo, [["Produk","Produk"]], {}, :disabled => true %></td>
				<td><%= f_det.text_field :quantity_promo, :disabled => true %></td>
				<td><%= f_det.select :type_target, [["Barang","Barang"],["Persen", "Persen"]], {}, :onchange => "get_type_target(this, #{i})", :disabled => true %></td>
				<td>
					<span class="type_target">
						<%= f_det.select :value_target, @products.collect{|prod| ["(#{prod.vendor.vendor_name}) #{prod.item_code} - #{prod.item_description}", prod.id] }, :disabled => true %>
					</span>
				</td>
				<td><%= f_det.text_field :quantity_target, :disabled => true %></td>
			</tr>
		<% end %>
	<% end %>
</table>
<br/>
<%= f.submit %>

app/views/promos/shared/_results.html.erb
<p id="notice"><%= flash[:notice] %></p>
<table border="1">
	<tr>
		<td>Promo Description</td>
		<td>Start Date From</td>
		<td>End Date From</td>
		<td>Detail Promo</td>
	</tr>
	<% if promos.blank? %>
		<tr>
			<td colspan="4">Data tidak ditemukan</td>
		</tr>
	<% else %>
		<% promos.each do |promo| %>
			<tr>
				<td><%= promo.promo_description %></td>
				<td><%= promo.start_date_promo.localtime.strftime("%d %B %Y") %></td>
				<td><%= promo.end_date_promo.localtime.strftime("%d %B %Y") %></td>
				<td><%= link_to "Detail", promo_path(promo) %></td>
			</tr>
		<% end %>
	<% end %>
</table>

<%= link_to "Tambah Promo", new_promo_path %>